FROM node

WORKDIR /app

COPY package.json /app/package.json
RUN npm install
COPY ca.pem /app/ca.pem
COPY dbSchema/ /app/dbSchema/
COPY controllers/ /app/controllers/
COPY socketservice.js /app/socketservice.js

CMD ["node", "socketservice.js"]
