FROM node

WORKDIR /app

COPY package.json /app/package.json
RUN npm install
COPY dbSchema/ /app/dbSchema/
COPY controllers/ /app/controllers/
COPY dbinsertionkafka.js /app/dbinsertionkafka.js

CMD ["node", "dbinsertionkafka.js"]
